// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0VV1Z7z4VorOGHELMGQ0x9sx-WsXI3nc',
    appId: '1:799397622719:web:1fafabb8f6bac98bf0e70a',
    messagingSenderId: '799397622719',
    projectId: 'fridgescanner-1337',
    authDomain: 'fridgescanner-1337.firebaseapp.com',
    databaseURL: 'https://fridgescanner-1337-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fridgescanner-1337.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfXMpTvZm1oBGX9hUr9-kAnNySNU-b878',
    appId: '1:799397622719:android:92651a2ab93de4c5f0e70a',
    messagingSenderId: '799397622719',
    projectId: 'fridgescanner-1337',
    databaseURL: 'https://fridgescanner-1337-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fridgescanner-1337.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCediTbYTjqiaOI-97BJtMoh-yE9BAIxRk',
    appId: '1:799397622719:ios:a6d00c1a7a273525f0e70a',
    messagingSenderId: '799397622719',
    projectId: 'fridgescanner-1337',
    databaseURL: 'https://fridgescanner-1337-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fridgescanner-1337.firebasestorage.app',
    iosBundleId: 'com.example.fridgescannerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCediTbYTjqiaOI-97BJtMoh-yE9BAIxRk',
    appId: '1:799397622719:ios:a6d00c1a7a273525f0e70a',
    messagingSenderId: '799397622719',
    projectId: 'fridgescanner-1337',
    databaseURL: 'https://fridgescanner-1337-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fridgescanner-1337.firebasestorage.app',
    iosBundleId: 'com.example.fridgescannerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0VV1Z7z4VorOGHELMGQ0x9sx-WsXI3nc',
    appId: '1:799397622719:web:28db5feb07544fbbf0e70a',
    messagingSenderId: '799397622719',
    projectId: 'fridgescanner-1337',
    authDomain: 'fridgescanner-1337.firebaseapp.com',
    databaseURL: 'https://fridgescanner-1337-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fridgescanner-1337.firebasestorage.app',
  );
}
